version: '3.2'

services:

  webshotter_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/requirements.dev.txt
    container_name: webshotter
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
      - OPENSSL_CONF=~/bin/etc/openssl.cnf
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  postgres:
      image: postgres:10
      container_name: webshotter_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432

#  test:
#    <<: *app
#    container_name: webshotter_test
#    ports:
#      - 8082:8082
#    entrypoint: py.test -v -p no:warnings
#    command: ''
